package com.gaoyun.yanyou_kototomo.ui.base.theme.colors

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object OriginalColors {
    val primaryLight = Color(0xFF7E570E)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFFFDDAF)
    val onPrimaryContainerLight = Color(0xFF281800)
    val secondaryLight = Color(0xFF6E5B40)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFF9DFBB)
    val onSecondaryContainerLight = Color(0xFF261904)
    val tertiaryLight = Color(0xFF506441)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFF2f402c)
    val onTertiaryContainerLight = Color(0xFFd8edd1)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF410002)
    val backgroundLight = Color(0xFFFFF8F3)
    val onBackgroundLight = Color(0xFF201B13)
    val surfaceLight = Color(0xFFFFF8F3)
    val onSurfaceLight = Color(0xFF201B13)
    val surfaceVariantLight = Color(0xFFEFE0CF)
    val onSurfaceVariantLight = Color(0xFF4F4539)
    val outlineLight = Color(0xFF817567)
    val outlineVariantLight = Color(0xFFD2C4B4)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF362F27)
    val inverseOnSurfaceLight = Color(0xFFFBEFE2)
    val inversePrimaryLight = Color(0xFFF2BE6E)
    val surfaceDimLight = Color(0xFFE4D8CC)
    val surfaceBrightLight = Color(0xFFFFF8F3)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFFEF2E5)
    val surfaceContainerLight = Color(0xFFF8ECDF)
    val surfaceContainerHighLight = Color(0xFFF2E6DA)
    val surfaceContainerHighestLight = Color(0xFFEDE1D4)

    val primaryDark = Color(0xFFF2BE6E)
    val onPrimaryDark = Color(0xFF442C00)
    val primaryContainerDark = Color(0xFF614000)
    val onPrimaryContainerDark = Color(0xFFFFDDAF)
    val secondaryDark = Color(0xFFDCC3A1)
    val onSecondaryDark = Color(0xFF3D2E16)
    val secondaryContainerDark = Color(0xFF55442A)
    val onSecondaryContainerDark = Color(0xFFF9DFBB)
    val tertiaryDark = Color(0xFFB6CEA3)
    val onTertiaryDark = Color(0xFF233517)
    val tertiaryContainerDark = Color(0xFF222e20)
    val onTertiaryContainerDark = Color(0xFFD2EABD)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF18130B)
    val onBackgroundDark = Color(0xFFEDE1D4)
    val surfaceDark = Color(0xFF18130B)
    val onSurfaceDark = Color(0xFFEDE1D4)
    val surfaceVariantDark = Color(0xFF4F4539)
    val onSurfaceVariantDark = Color(0xFFD2C4B4)
    val outlineDark = Color(0xFF9B8F80)
    val outlineVariantDark = Color(0xFF4F4539)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFEDE1D4)
    val inverseOnSurfaceDark = Color(0xFF362F27)
    val inversePrimaryDark = Color(0xFF7E570E)
    val surfaceDimDark = Color(0xFF18130B)
    val surfaceBrightDark = Color(0xFF3F382F)
    val surfaceContainerLowestDark = Color(0xFF120D07)
    val surfaceContainerLowDark = Color(0xFF201B13)
    val surfaceContainerDark = Color(0xFF241F17)
    val surfaceContainerHighDark = Color(0xFF2F2921)
    val surfaceContainerHighestDark = Color(0xFF3A342B)

    val lightScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    val darkScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
}